# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5332a8aa11d41b8a672479b55e397672b6ab54d02fec31b629ea356fc480560c09547d46459900784d6b5df92ebed887edb5f73a1d1725c5d1227d8feead5064

test:
  secret_key_base: 66c1b0dd882e601577e7c493aa84fddeeb244236efd66173b201898bb136ff494bebeb0c0df58c24e49184be3deb89442d5fcbccec2328f42bf1f6d17d64818b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
